#
# Dockerfile to build a self-contained full RT image.
#
# Best practice would be to remove the realtime-application directory first.
#

FROM registry.allocatesoftware.com/jenk-test-1

RUN mkdir /usr/local/blah



