#
# Dockerfile to build a self-contained full RT image.
#
# Best practice would be to remove the realtime-application directory first.
#

FROM registry.allocatesoftware.com/realtime-dev-one_build:40

RUN mkdir /usr/local/blah



